bind_addr = ":5555"
log_level = "debug"
database_url = "user=postgres password=123456 host=localhost port=5000 dbname=Nats_Streaming sslmode=disable"
stan_subj = "orders"
stan_clusterID = "test-cluster"